-- Eliminar tablas en orden correcto (primero las que tienen dependencias)
DROP TABLE IF EXISTS PATIENTS;
DROP TABLE IF EXISTS DENTISTS;
DROP TABLE IF EXISTS ADDRESSES;

-- Crear tablas en orden correcto (primero las independientes)
CREATE TABLE ADDRESSES (ID INT AUTO_INCREMENT PRIMARY KEY,
STREET VARCHAR(100) NOT NULL,
NUMBER INT NOT NULL,
LOCATION VARCHAR(100) NOT NULL,
PROVINCE VARCHAR(100) NOT NULL);

CREATE TABLE PATIENTS (ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DNI VARCHAR(100) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ADDRESS_ID INT NOT NULL,
FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ID));

CREATE TABLE DENTISTS (ID INT AUTO_INCREMENT PRIMARY KEY,
REGISTRATION INT NOT NULL,
NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL);

INSERT INTO ADDRESSES(STREET, NUMBER, LOCATION, PROVINCE)
VALUES ('Calle A',101,'Luján de Cuyo','Mendoza');

INSERT INTO PATIENTS (NOMBRE, APELLIDO, EMAIL, DNI, FECHA_INGRESO, ADDRESS_ID)
VALUES ('Juan','Perez', 'prueba@gmail.com', '1245487','2023-11-10',1);

INSERT INTO DENTISTS (REGISTRATION, NAME, LAST_NAME)
VALUES (123,'Carlos','Muelas');